// This file is generated by scripts/generate-runtime-migrations.mjs.
// Regenerate it whenever a migration is added or changed.
import type { RuntimeDatabaseMigration } from "./setup-database-migrations.types";

export const runtimeDatabaseMigrations: RuntimeDatabaseMigration[] = [
  {
    "name": "0000_init.sql",
    "statements": [
      "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`store_name` text NOT NULL,\n\t`store_slug` text NOT NULL,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`active_store_id` text,\n\t`github_oauth_hostname` text,\n\t`created_at` text NOT NULL\n);",
      "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);",
      "CREATE UNIQUE INDEX `users_store_slug_unique` ON `users` (`store_slug`);",
      "CREATE TABLE `stores` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`logo_image_url` text,\n\t`cover_image_url` text,\n\t`email_from` text,\n\t`email_reply_to` text,\n\t`payment_credential_source_store_id` text,\n\t`payment_gateway` text DEFAULT 'paypal' NOT NULL,\n\t`github_credential_source_store_id` text,\n\t`affiliates_enabled` integer DEFAULT 1 NOT NULL,\n\t`affiliate_commission_type` text DEFAULT 'percentage' NOT NULL,\n\t`affiliate_commission_value` real DEFAULT 10 NOT NULL,\n\t`affiliate_commission_duration` text DEFAULT 'one_time' NOT NULL,\n\t`affiliate_attribution_model` text DEFAULT 'last_click' NOT NULL,\n\t`email_campaigns_enabled` integer DEFAULT 1 NOT NULL,\n\t`abandoned_checkout_reminders_enabled` integer DEFAULT 0 NOT NULL,\n\t`currency` text DEFAULT 'USD' NOT NULL,\n\t`transaction_fee_type` text DEFAULT 'fixed' NOT NULL,\n\t`transaction_fee_value` integer DEFAULT 0 NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `stores_slug_idx` ON `stores` (`slug`);",
      "CREATE INDEX `stores_user_idx` ON `stores` (`user_id`);",
      "CREATE TABLE `products` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`store_id` text,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`name` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`price` integer NOT NULL,\n\t`transaction_fee_type` text DEFAULT 'fixed' NOT NULL,\n\t`transaction_fee_value` integer DEFAULT 0 NOT NULL,\n\t`currency` text DEFAULT 'USD' NOT NULL,\n\t`status` text DEFAULT 'draft' NOT NULL,\n\t`image_url` text,\n\t`delivery_content` text,\n\t`product_files` text DEFAULT '[]' NOT NULL,\n\t`generate_license` integer DEFAULT 0 NOT NULL,\n\t`license_type` text DEFAULT 'standard' NOT NULL,\n\t`license_update_period_unit` text,\n\t`license_update_period_count` integer DEFAULT 1 NOT NULL,\n\t`billing_type` text DEFAULT 'one_time' NOT NULL,\n\t`interval_unit` text,\n\t`interval_count` integer DEFAULT 1 NOT NULL,\n\t`trial_days` integer DEFAULT 0 NOT NULL,\n\t`github_repo_owner` text,\n\t`github_repo_name` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `orders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`store_id` text,\n\t`product_id` text NOT NULL,\n\t`product_name` text NOT NULL,\n\t`product_description` text,\n\t`product_price` integer,\n\t`delivery_content` text,\n\t`product_files` text DEFAULT '[]' NOT NULL,\n\t`github_repo_owner` text,\n\t`github_repo_name` text,\n\t`amount` integer NOT NULL,\n\t`currency` text NOT NULL,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`customer_email` text NOT NULL,\n\t`customer_name` text,\n\t`discount_code` text,\n\t`discount_amount` integer DEFAULT 0 NOT NULL,\n\t`transaction_fee_amount` integer DEFAULT 0 NOT NULL,\n\t`affiliate_id` text,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`paypal_order_id` text,\n\t`paypal_capture_id` text,\n\t`stripe_checkout_session_id` text,\n\t`stripe_payment_intent_id` text,\n\t`gateway` text DEFAULT 'paypal' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`paid_at` text,\n\t`github_username` text,\n\t`github_access_status` text DEFAULT 'not_required' NOT NULL,\n\t`github_access_managed` integer DEFAULT 0 NOT NULL,\n\t`github_invitation_id` text,\n\t`github_access_error` text,\n\t`github_access_granted_at` text,\n\t`github_access_revoked_at` text,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `checkout_reminders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`store_id` text NOT NULL,\n\t`product_id` text NOT NULL,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`customer_email` text NOT NULL,\n\t`customer_name` text,\n\t`product_name` text NOT NULL,\n\t`checkout_url` text NOT NULL,\n\t`due_at` text NOT NULL,\n\t`sent_at` text,\n\t`cancelled_at` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `checkout_reminders_store_product_environment_email_idx` ON `checkout_reminders` (`store_id`,`product_id`,`environment`,`customer_email`);",
      "CREATE INDEX `checkout_reminders_due_idx` ON `checkout_reminders` (`due_at`,`sent_at`,`cancelled_at`);",
      "CREATE TABLE `github_connections` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`github_user_id` text NOT NULL,\n\t`login` text NOT NULL,\n\t`access_token_encrypted` text NOT NULL,\n\t`scopes` text DEFAULT '' NOT NULL,\n\t`connected_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `paypal_connections` (\n\t`user_id` text NOT NULL,\n\t`client_id` text NOT NULL,\n\t`client_secret_encrypted` text NOT NULL,\n\t`mode` text DEFAULT 'sandbox' NOT NULL,\n\t`merchant_email` text,\n\t`webhook_id` text,\n\t`webhook_url` text,\n\t`webhook_status` text DEFAULT 'not_configured' NOT NULL,\n\t`webhook_error` text,\n\t`connected_at` text NOT NULL,\n\tPRIMARY KEY (`user_id`,`mode`),\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `stripe_connections` (\n\t`user_id` text NOT NULL,\n\t`secret_key_encrypted` text NOT NULL,\n\t`webhook_secret_encrypted` text,\n\t`account_id` text NOT NULL,\n\t`mode` text DEFAULT 'sandbox' NOT NULL,\n\t`connected_at` text NOT NULL,\n\tPRIMARY KEY (`user_id`,`mode`),\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `feature_records` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`feature` text NOT NULL,\n\t`title` text NOT NULL,\n\t`subtitle` text,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`data` text DEFAULT '{}' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `feature_records_user_feature_idx` ON `feature_records` (`user_id`,`feature`);",
      "CREATE TABLE `app_licenses` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`license_key_encrypted` text NOT NULL,\n\t`license_key_prefix` text NOT NULL,\n\t`instance_id` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`plan` text DEFAULT 'pro' NOT NULL,\n\t`features` text DEFAULT '[]' NOT NULL,\n\t`manage_url` text,\n\t`expires_at` text,\n\t`last_validated_at` text,\n\t`validation_error` text,\n\t`activated_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE UNIQUE INDEX `app_licenses_instance_id_unique` ON `app_licenses` (`instance_id`);",
      "CREATE TABLE `api_keys` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`key_prefix` text NOT NULL,\n\t`key_hash` text NOT NULL,\n\t`last_used_at` text,\n\t`expires_at` text,\n\t`revoked_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `api_keys_key_hash_unique` ON `api_keys` (`key_hash`);",
      "CREATE INDEX `api_keys_user_idx` ON `api_keys` (`user_id`);",
      "CREATE TABLE `notifications` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`type` text NOT NULL,\n\t`title` text NOT NULL,\n\t`message` text,\n\t`href` text,\n\t`source_key` text NOT NULL,\n\t`read_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `notifications_user_created_idx` ON `notifications` (`user_id`,`created_at`);",
      "CREATE INDEX `notifications_user_read_idx` ON `notifications` (`user_id`,`read_at`);",
      "CREATE UNIQUE INDEX `notifications_user_environment_source_idx` ON `notifications` (`user_id`,`environment`,`source_key`);",
      "CREATE TABLE `customer_accounts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text,\n\t`avatar_image_url` text,\n\t`password_hash` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE UNIQUE INDEX `customer_accounts_email_unique` ON `customer_accounts` (`email`);",
      "CREATE TABLE `customer_access_tokens` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`customer_id` text NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`expires_at` text NOT NULL,\n\t`used_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`customer_id`) REFERENCES `customer_accounts`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `customer_access_tokens_token_hash_unique` ON `customer_access_tokens` (`token_hash`);",
      "CREATE INDEX `customer_access_tokens_customer_idx` ON `customer_access_tokens` (`customer_id`);",
      "CREATE INDEX `customer_access_tokens_expiry_idx` ON `customer_access_tokens` (`expires_at`);",
      "CREATE TRIGGER `users_single_account_insert`\nBEFORE INSERT ON `users`\nWHEN EXISTS (SELECT 1 FROM `users`)\nBEGIN\n\tSELECT RAISE(ABORT, 'Only one account is allowed');\nEND;"
    ]
  },
  {
    "name": "0001_primary_store.sql",
    "statements": [
      "ALTER TABLE `users` ADD `primary_store_id` text;",
      "UPDATE `users`\nSET `primary_store_id` = `active_store_id`\nWHERE `primary_store_id` IS NULL;"
    ]
  },
  {
    "name": "0002_query_indexes.sql",
    "statements": [
      "CREATE INDEX `products_slug_idx` ON `products` (`slug`);",
      "CREATE INDEX `products_user_store_environment_created_idx` ON `products` (`user_id`,`store_id`,`environment`,`created_at`);",
      "CREATE INDEX `orders_user_store_environment_created_idx` ON `orders` (`user_id`,`store_id`,`environment`,`created_at`);",
      "CREATE INDEX `orders_paypal_order_environment_idx` ON `orders` (`paypal_order_id`,`environment`);",
      "CREATE INDEX `orders_paypal_capture_environment_idx` ON `orders` (`paypal_capture_id`,`environment`);",
      "CREATE INDEX `orders_customer_environment_status_created_idx` ON `orders` (lower(`customer_email`),`environment`,`status`,`created_at`);",
      "CREATE INDEX `orders_reminder_purchase_lookup_idx` ON `orders` (`store_id`,`product_id`,lower(`customer_email`),`status`,`created_at`);",
      "CREATE INDEX `feature_records_user_feature_environment_created_idx` ON `feature_records` (`user_id`,`feature`,`environment`,`created_at`);",
      "CREATE INDEX `feature_records_customer_portal_idx` ON `feature_records` (lower(`subtitle`),`environment`,`feature`,`updated_at`);",
      "CREATE INDEX `feature_records_paypal_subscription_idx` ON `feature_records` (`feature`,`environment`,json_extract(`data`, '$.paypalSubscriptionId'));"
    ]
  },
  {
    "name": "0003_inactive_stores.sql",
    "statements": [
      "ALTER TABLE `stores` ADD `is_active` integer DEFAULT 1 NOT NULL;"
    ]
  },
  {
    "name": "0004_custom_product_amount.sql",
    "statements": [
      "ALTER TABLE `products` ADD `custom_amount_enabled` integer DEFAULT 0 NOT NULL;"
    ]
  },
  {
    "name": "0005_campaign_tracking.sql",
    "statements": [
      "CREATE TABLE `campaign_deliveries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`campaign_id` text NOT NULL,\n\t`subscriber_id` text,\n\t`email` text NOT NULL,\n\t`opened_at` text,\n\t`clicked_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`campaign_id`) REFERENCES `feature_records`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `campaign_deliveries_campaign_idx` ON `campaign_deliveries` (`campaign_id`);",
      "CREATE INDEX `campaign_deliveries_email_idx` ON `campaign_deliveries` (`email`);"
    ]
  },
  {
    "name": "0006_customer_email_preferences.sql",
    "statements": [
      "CREATE TABLE `customer_email_preferences` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`store_id` text NOT NULL,\n\t`email` text NOT NULL,\n\t`marketing_enabled` integer DEFAULT 1 NOT NULL,\n\t`product_updates_enabled` integer DEFAULT 1 NOT NULL,\n\t`affiliate_updates_enabled` integer DEFAULT 1 NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `customer_email_preferences_store_email_unique` ON `customer_email_preferences` (`store_id`,`email`);",
      "CREATE INDEX `customer_email_preferences_email_idx` ON `customer_email_preferences` (lower(`email`));"
    ]
  },
  {
    "name": "0007_outbound_webhooks.sql",
    "statements": [
      "CREATE TABLE `webhooks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`store_id` text NOT NULL,\n\t`environment` text DEFAULT 'sandbox' NOT NULL,\n\t`name` text NOT NULL,\n\t`url` text NOT NULL,\n\t`secret_encrypted` text NOT NULL,\n\t`events` text DEFAULT '[]' NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`store_id`) REFERENCES `stores`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `webhooks_user_store_environment_idx` ON `webhooks` (`user_id`,`store_id`,`environment`);",
      "CREATE TABLE `webhook_deliveries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`webhook_id` text NOT NULL,\n\t`event_name` text NOT NULL,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`request_body` text NOT NULL,\n\t`response_status` integer,\n\t`response_body` text,\n\t`error` text,\n\t`duration_ms` integer,\n\t`created_at` text NOT NULL,\n\t`completed_at` text,\n\tFOREIGN KEY (`webhook_id`) REFERENCES `webhooks`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `webhook_deliveries_webhook_created_idx` ON `webhook_deliveries` (`webhook_id`,`created_at`);"
    ]
  },
  {
    "name": "0008_webhook_auth.sql",
    "statements": [
      "ALTER TABLE `webhooks` ADD `auth_encrypted` text;"
    ]
  },
  {
    "name": "0009_order_custom_data.sql",
    "statements": [
      "ALTER TABLE `orders` ADD `custom` text DEFAULT '{}' NOT NULL;"
    ]
  },
  {
    "name": "0010_webhook_products.sql",
    "statements": [
      "ALTER TABLE `webhooks` ADD `product_ids` text DEFAULT '[]' NOT NULL;"
    ]
  }
];
